apiVersion: v2
appVersion: "2.6.9"
description: This server allows you to sync any Joplin client
name: joplin-server
version: 5.0.17
kubeVersion: '>=1.16.0-0'
keywords:
  - joplin
  - notes
home: https://github.com/truecharts/apps/tree/master/charts/stable/jopplin-server
icon: https://truecharts.org/_static/img/appicons/joplin-server-icon.png
sources:
  - https://github.com/laurent22/joplin/tree/dev/packages/server
  - https://github.com/laurent22/joplin
  - https://hub.docker.com/r/joplin/server
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.25
- condition: postgresql.enabled
  name: postgresql
  repository: https://truecharts.org/
  version: 6.0.37
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
